enum SELECTED_GOODS {
  SET_SELECTED_GOODS = 'SET_SELECTED_GOODS',
  ADD_SELECTED_GOODS_ITEM = 'ADD_SELECTED_GOODS_ITEM',
  REMOVE_SELECTED_GOODS_ITEM = 'REMOVE_SELECTED_GOODS_ITEM',
}

export default SELECTED_GOODS
